/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2024-04-04 06:45:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.dto.EmployeDto;
import java.util.Iterator;
import java.util.List;

public final class EmployeListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("in.co.rays.dto.EmployeDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      in.co.rays.dto.EmployeDto dto = null;
      dto = (in.co.rays.dto.EmployeDto) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new in.co.rays.dto.EmployeDto();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("	<form action=\"EmployeListCtl\" method=\"post\">\r\n");
      out.write("		<h1 align=\"center\">Employe List</h1>\r\n");
      out.write("		");

			List list = (List) request.getAttribute("list");
			Iterator it = list.iterator();
			int index = 1;
			String msg = (String) request.getAttribute("msg");
			if (msg != null) {
		
      out.write("\r\n");
      out.write("		<h3 align=\"center\" style=\"color: red\">");
      out.print(msg);
      out.write("</h3>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("		&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		<table align=\"center\">\r\n");
      out.write("\r\n");
      out.write("	  <tr >\r\n");
      out.write("      <td>Name</th>\r\n");
      out.write("      <td><input type=\"text\" name=\"name\">\r\n");
      out.write("      <input type=\"submit\" name=\"operation\" value=\"search\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</table>\r\n");
      out.write("		&nbsp;\r\n");
      out.write("		<table align=\"center\" width=\"100%\" cellpadding=7px border=\"2\">\r\n");
      out.write("			<tr align=\"center\"  bgcolor=\"aqua\">\r\n");
      out.write("				<th>Select</th>\r\n");
      out.write("				<th>S.NO</th>\r\n");
      out.write("				<th> Name</th>\r\n");
      out.write("				<th>DOB</th>\r\n");
      out.write("				<th>Company</th>\r\n");
      out.write("				<th>Department</th>\r\n");
      out.write("				<th>Salary</th>\r\n");
      out.write("				<th>Edit</th>\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

				while (it.hasNext()) {
					dto = (EmployeDto) it.next();
			
      out.write("\r\n");
      out.write("			<tr align=\"center\">\r\n");
      out.write("				<td><input type=\"checkbox\"  name=\"ids\" value=\"");
      out.print(dto.getId());
      out.write("\"></td>\r\n");
      out.write("				<td>");
      out.print(index++);
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getName());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getDob());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getCompany());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getDepartment());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(dto.getSalary());
      out.write("</td>\r\n");
      out.write("				\r\n");
      out.write("				<td><a href=\"EmployeCtl?id=");
      out.print(dto.getId());
      out.write("\">[edit]</a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("		<table align=\"center\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th></th>\r\n");
      out.write("				<td><input type=\"submit\" name=\"operation\" value=\"delete\"></td>\r\n");
      out.write("				<th></th>\r\n");
      out.write("				<!-- <td><input type=\"submit\" name=\"operation\" value=\"new\"></td>\r\n");
      out.write("				<td><input type=\"reset\"></td> -->\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
